check:
  http-url: http://www.baidu.com
  https-url: https://www.baidu.com
  anonymous-url: http://httpbin.org/get
  post-url: http://httpbin.org/post
  thread: 100
  timeout: 5

rabbitmq:
  host: service-rabbitmq
  port: 5672
  username: sage
  password: '!EVk@vSZSx9S'
  virtual-host: /
